# Generated by Django 2.2.2 on 2019-08-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_auto_20190821_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='productss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=20)),
                ('pro_name', models.CharField(max_length=100)),
                ('com_email', models.EmailField(max_length=254)),
                ('com_contact', models.CharField(max_length=12)),
                ('com_address', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'productss',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
