# Generated by Django 2.2.2 on 2019-08-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
