# Generated by Django 2.2.2 on 2019-08-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_employee_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='file',
            new_name='file_upload',
        ),
    ]
