# Generated by Django 3.0.1 on 2019-12-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_auto_20190824_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_pic',
        ),
    ]
