# Generated by Django 3.0.1 on 2019-12-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_auto_20191225_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='file_upload',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
