# Generated by Django 3.0.1 on 2019-12-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0009_auto_20191225_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_pic',
        ),
    ]
